Camera Class
gizmokis/resin pull request #13
Opened 2024-11-18 20:02 UTC by adamieck

simple yet uhhh... simple 🎥

2024-11-19 13:53 UTC, kubazuch requested changes

2024-11-19 13:53 UTC, kubazuch commented on libresin/libresin/core/camera.hpp
Having more time, I reconsidered the design of `Camera` class. At the end of the day we never need to change the in-world camera dimensions. We only care about _apparent_ `fov` and `aspect_ratio`.

Because of this I propose new design of `Camera`:
- public `transform` and `is_orthographic` 
- private `fov`, `aspect_ratio`, `near_plane` and `far_plane`
- public `(effective_)fov()` (you can come up with the name, orthographic camera has no concept of `fov`, but maybe we can still call this just `fov` -- u do u :p), `aspect_ratio()`, `near_plane()`, `far_plane()`, `width()`, `height()` getters
- public `view_matrix()` and `inverse_view_matrix()` getters
- public `set_(effective_)fov()`, `set_aspect_ratio()`, `set_near_plane()`, `set_far_plane()`, setters 
- **_one of_** _optional_ optimisations, as `width` and `height` change **_very rarely_**
    - _optional:_ `width` and `height` fields calculated in constructor and setters
    - _optional:_ `width` and `height` caching with `dirty` flag 

This solution requires less bloated code and allows dynamic change between camera types. It's also more intuitive, as user may think that `width` and `height` are display-based.

2024-11-19 14:34 UTC, migoox commented on libresin/libresin/core/camera.hpp
+1, one `Camera` class is enough, currently we still have the `is_orthographic` inside of the abstract `Camera` which is set in the derived classes and it feels not right

2024-11-22 10:32 UTC, kubazuch approved these changes

2024-11-22 12:03 UTC, merged